name = "MattTrack"
uuid = "6acdfc63-f9cf-4e23-a939-03aab3349018"
authors = ["mattsignorelli <mgs255@cornell.edu> and contributors"]
version = "1.0.0-DEV"

[deps]
GTPSA = "b27dd330-f138-47c5-815b-40db9dd9b6e8"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
GTPSA = "1.4.1"
LinearAlgebra = "1.11.0"
OrderedCollections = "1.8.0"
StaticArrays = "1.9.13"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
